apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      serviceAccountName: csi-secrets-store-driver-sa
      containers:
      - name: postgres
        image: postgres:15
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
        - name: POSTGRES_PASSWORD
          value: "/mnt/secrets-store/secrets-manager-password"
        - name: POSTGRES_USER
          value: "/mnt/secrets-store/secrets-manager-username"  
        - name: POSTGRES_DB
          value: "/mnt/secrets-store/secrets-manager-dbname"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: postgres-secrets
